### ISSUE TITLE
MobEscape: Players die before reaching map border.

### ISSUE THREAD

**Issue by YouGamePlayHD** [MysticCity/MinigamesAPI#126]
Hi, here is another thing about MobEscape:
With die-below-bedrock set to false, players die before reaching the map borders. That is a problem because if you build a map that has some areas far below the starting point, the players die even though they jump legally. What is the death in this case defined by? So it would be a great thing making players die when they leave the map borders.

**Comment by mepeisen** [comment]
This config option is present in 4 games:
DeathRun, GunGame, MobEscape, Splegg

It defaults to 4 and to th following special values in the games:
- Splegg: 20
- SkyWars: 100
- FlyingCars: 100
- DeathRun: 15

If you set the config option to true it will set the value to 100.
Setting the config option to a numeric value will set it to the given value.


It controls when players automatically lose the game. It takes the players location y coordinate and adds the given value. If the result is below the FIRST spwna y coordinate the player looses.
Example:
- The spawn is set to coordinat 10/40/10 (y-coordinate 40).
- The value is 30.
- The player will loose while moving to any coordinate BELOW xx/10/zz (40 subtract by 30 = 10).

In version 2.0 the behaviour will change. The config option should be removed without any replacements. Instead there will be gaming rules bound to the arena bound itself.

Notice: In MobEscape there seems to be some special code. It takes not only the first players spawn but the arena bounds itself. Seems to be very confusing.
I decided to not remove the code or change it to much because this may break too many existing arenas.
