### ISSUE TITLE
[MGDeathrun] Cannot run /dr setspecbounds

### ISSUE THREAD

**Issue by logicalPolaris** [MysticCity/MinigamesAPI#166]
![screenshot_36](https://cloud.githubusercontent.com/assets/11083026/19017238/d68280ba-87e7-11e6-8bd8-cc7f4c143e9b.png)

Running the command keeps suggesting that I'm using it wrong, when I am not.

My arena is called "Deathrun",

**Comment by mepeisen** [comment]
fixed in 1.14.14.
Please retry with newest snapshot or wait for the release.

I added some changes.
1) command "/<game> spectate <arena>" is now secured by a permission. There may be admins that do not want to let users join spectator mode. Maybe a team is talking in teamspeak and a spectator helps a team to win. That's not good.
2) there is now a spectator sign to join on the same server
3) there is a spectator sign to join over bungeecord

See https://github.com/MysticCity/MinigamesAPI/wiki/Admin-Spectating for details

Download at http://www.minigameslib.de/downloads_en.php
