### ISSUE TITLE
Spectator doesn't transport to spectator area

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#188]
Environment: Spigot 1.11.2 latest, MG 1.14.14-2016-12-31.

What occurred:
```player X joined splegg arena Spleef via a join sign```
player X was transported to the Spleef lobby
```/sp start Spleef```
player X was transported to spawnpoint in the Spleef arena
game started after countdown (10)
```player X removed a few blocks by hurling snowballs```
```right-click spectate sign```
no transportation, no log errors or warnings
```/sp spectate Spleef```
game ended, winner player X
arena Spleef was rebuilt
no other log entries, no errors or warnings
player X and myself were transported back to main lobby

What I hoped: That I would spectate while player X played.

**Comment by mepeisen** [comment]
signs were fixed. They work for now. Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next 2 hours.
The underlying problem you lost the game is simple: this is not a single player game. Letting someone join spectators marks them for losing the game. As there is only one player left (still one player) he automatically wins.
This problem is already covered in #80

In 2.0 we should not have the problem because joining only for spectation will not influence the game itself. I will check this bug in 2.0

**Comment by SlimeDog** [comment]
Sorry I wasn't clear. The only problem I perceived was the lack of spectator mode. The rest was just the recipe that I used to get there. I appreciate that games are not single-player.

**Comment by mepeisen** [comment]
documentation: https://github.com/MysticCity/MinigamesAPI/wiki/Admin-Spectating ;-)

**Comment by SlimeDog** [comment]
**/sc spectate LittleSnake** (for example) works only if a game has been started.
> There is no started game!

I was hoping that it would transport me to the specspawn of an arena, to watch games _as_ they start.

**Comment by mepeisen** [comment]
sry, not yet possible. But it will be possible in 2.0

**Comment by SlimeDog** [comment]
Closed due to dev abandonment.
