### ISSUE TITLE
Development Error & Deprecation

### ISSUE THREAD

**Issue by CrolynX** [MysticCity/MinigamesAPI#212]
Hi, so first, im making a Plugin with MinigamesLib.

My first Problem is that most of the functions are deprecated, so i don't know what of these i should use :/

The second is, the Game throws me an error everytime i use an Command that uses the config.yml (it doesnt get generated)

```java
public void onEnable(){
	api = MinigamesAPI.setupAPI(this, "Paintball", IArena.class);
}
```

**Comment by Emalton** [comment]
Having the same issue.

**Comment by mepeisen** [comment]
The deprecated functions can be used. They won't be replaced in 1.14.15. But notice the javadocs. Some of the methods are directly returning the underlying lists and you should not manipulate the lists because this may cause bugs.

The deprecations were set because I started refactoring and later on I decided to completly rewrite the system.

There will be a migration guide for migrating games from 1.X to upcoming version 2.X

**Comment by mepeisen** [comment]
For the second error it is fixed in latest snapshot. You may manually work around the problem by using the other setupAPI method (this one using tons of parameters). Or directly invoke the following in your onEnable:
new DefaultConfig(this, false); // force initialization of config.yml

the latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
