### ISSUE TITLE
Conquer, problem with check points

### ISSUE THREAD

**Issue by Ancard** [MysticCity/MinigamesAPI#213]
Well, the problem is this.
When two players fight for a checkpoint they enter and leave the checkpoint several times in a couple of seconds, this causes the checkpoint to break. The checkpoint after breaking continues to change the color of the team that won the fight for the checkpoint, but the last cube (of the checkpoint) remains the color of the team that lost, sometimes it is in reverse. This prevents the team that is currently capturing the checkpoint, can capture it completely.
My idea and that can also be an improvement is to make the checkpoint pause when there are two players on it or it changes back to white and a delay before it starts to be captured by another team that can be established from the configuration.

**Comment by PantallazoAzul** [comment]
Same problem, I'm in Spigot 1.8.8

**Comment by mepeisen** [comment]
Please check the latest snapshot till next weekend. I fixed lags caused by scoreboard updates. Are there any additional problems and lags?
The problems you are describing can be caused by the scoreboard lags.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next two hours.

**Comment by mepeisen** [comment]
*closed* If this does not help please respond. I will reopen the issue.
