### ISSUE TITLE
TPS drops onPlayerDeath

### ISSUE THREAD

**Issue by Yhenko** [MysticCity/MinigamesAPI#259]
https://i.gyazo.com/2a4414d75d063feb8e2cf0ed050548ff.png
The tps drops to 18.50 - 19 :/

**Comment by mepeisen** [comment]
It is only in OITC? Or are there other games where you experience the problem?
Which version are you using (spigot and minigeameslib/oitc)?

**Comment by Yhenko** [comment]
i only have OITC in the server, 

Spigot version:
https://i.gyazo.com/e9ad4dedd35fc4439d0471cb778e0ba9.png

Oitc version:
https://i.gyazo.com/13e1f88d486620f1c07a9055550c2ee9.png

**Comment by mepeisen** [comment]
ok, there are some things happening in onPlayerDeath.
1. killer stats. --> Does it only happen when arena is going on? Or only happen when game stops because someone wins?
2. kill rewards? --> Did you add some kill rewards to config and what happens if you temporary disable kill rewards?
4. Message boradcast --> There is a message "x was killed by y". How many players are online in your world? Do you experience the same problem when only two or three players are there?
3. score board updates. In the past we got some performance issue on scoreborads.

**Comment by Yhenko** [comment]
the tps drops happen when the arena is going on, i dont have kill rewards and i play the game with 6-10 players and only 1 arena running :/
Another gyazo, only 5 playing in the arena (same world for arena / mainlobby and arenalobby)
https://gyazo.com/218a9a23ccbb05c03990bdc81c17a103

**Comment by mepeisen** [comment]
I played around with JProfiler. I used a minimalist setup with only two other plugins. However I cannot verify your problems.
Can you list all plugins You are using? Maybe there is a plugin doing something strange on the OITC code.

**Comment by mepeisen** [comment]
*closed* because of no response
