### ISSUE TITLE
Map reset 

### ISSUE THREAD

**Issue by xbxymax** [MysticCity/MinigamesAPI#286]
Can you add a setting?
rollback: true/false
When this is false 
The game will not reset the map 

I want to reset the map with other plug-ins

**Comment by xbxymax** [comment]
Or you can change the way you reset the map 
Uninstall the world 
Copy block file 
Load the world 
Loading arena

**Comment by mepeisen** [comment]
solved.
Add a config option to arenas.yml (arenas.[Name].smart_reset).
Defaults to true. You can set it to false for disabling smart_reset per arena.

Please notice: It will not disable the hard reset through reset console command. Because this works a bit different.
But I do not think you need to disable the hard reset.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.

**Comment by xbxymax** [comment]
Thank you very much 
I'll try different reset methods 
I believe that the command to save the configuration can also be overridden

**Comment by mepeisen** [comment]
> I believe that the command to save the configuration can also be overridden

Can you explain it?
