### ISSUE TITLE
Bungeecord

### ISSUE THREAD

**Issue by Mamaie** [MysticCity/MinigamesAPI#309]
Hello , I just put this plugin on my server but I have a question , the party system work on lobby ? I don t know how to make it , minigamesapi don t have a mysql and I want to use your bedwars , skywars plugins but I also want the party system work on hub , it is work but when I invite a player and teleport to a server It does not come after me.

**Comment by Mamaie** [comment]
I try to make party on lobby to work with my skywars server and bedwars server but the party list are not saved when I change the server..

**Comment by mepeisen** [comment]
sry for late response. The party system is not yet persistent. Once a game was joined the party is removed.

The bug you are talking (people not following you) is already fixed in latest snapshot of upcoming 1.14.18.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php

*closed* If this does not help please respond. I will reopen the issue.
