### ISSUE TITLE
Plugin file names

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#33]
Would you consider naming the JAR files the same as the plugins' internal names and configuration directories:
MGFlyingCars :: MGFlyingCars-*.jar instead of FlyingCars-*.jar
MGSnake :: MGSnake-*.jar instead of Snake-*.jar
etc.

No just for consistency, but also they would alphabetize nicely in the plugins/ directory (and therefore in my plugin manager).

**Comment by mepeisen** [comment]
not all games start with prefix 'MG'. I am wondering if I should rename the others.
ColorMatch -> MGColorMatch
HorseRacingPlus -> MGHorseRacingPlus
Jumper -> MGJumper
Sudoku -> MGSudoku

I don't care about names and it's fine for me to use prefix 'MG' for all the official Minigame-Libs games.

**Comment by SlimeDog** [comment]
You should do. :)

**Comment by mepeisen** [comment]
http://nexus.xworlds.eu/nexus/content/groups/mce/com/github/MCE-Plugins/MGBedWars-Plugin/1.14.9-SNAPSHOT/
Nice and sweet file names ;-)

**Comment by SlimeDog** [comment]
Apologies for keeping at this issue, but is there any reason to include "-Plugin" in the file names?

**Comment by mepeisen** [comment]
Yes. It is for not keeping the users confused that search the nexus for plugin jars manually.
At the moment there are already multiple maven jars/ builds for some of the games. For example Snake contains a parent pom and jars for each minecraft version because of the nms classes. In future there may be many other modules, specially for testing.
The suffix "Plugin" will hopefully make it clear with jar file is actually a spigot plugin.

If one uses maven to find the latest plugin version he will get it with suffix "Plugin". But you are always able to rename the jar file buy using maven-dependency-plugin.

To fit your personal 'beauty' needs the website (#23) I mentioned can contain symbolic links.
So that you are able to find jar files with naming "MGSnake-2016xxxxx.jar".

**Comment by SlimeDog** [comment]
Yep.  It was just a suggestion. I'll manage it at my end, whatever you guys decide.
