### ISSUE TITLE
MobEscape - Customisation of destroyed blocks

### ISSUE THREAD

**Issue by YouGamePlayHD** [MysticCity/MinigamesAPI#64]
Another config file entry: You should be able to control the percentage of falling blocks (when the mob touches them). If you have a really huge map with thousands of blocks everything starts lagging and if you don't have a good PC, Minecraft will crash or the game will be unplayably laggy. 
The entry could be like this:

`falling-blocks-rate = 50`

That would mean that only 50% of the blocks fall - the rest just disappears. Minplex uses the same technique to make the game playable for all players - not only the ones owning a good PC.

Greetings,
YouGamePlayHD

**Comment by mepeisen** [comment]
closed.
test with newest snapshot from http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.11-SNAPSHOT/Minigames-All-1.14.11-20160820.112940-13-bin.zip
Notice: Due to incompatible api changes you need to upgrade the minigames jar too. Not only MGMobEscape.

**Comment by YouGamePlayHD** [comment]
I cannot find this setting in arena.yml?
