### ISSUE TITLE
MobEscape: Regen falling blocks lastly 

### ISSUE THREAD

**Issue by YouGamePlayHD** [MysticCity/MinigamesAPI#68]
Another suggestion that will certainly improve MobEscape:
If you have a map with much sand (I do have a beach map XD) or gravel, there will be a problem after the game with regenerating the blocks: the priorities are the same, so sand gets generated 50:50 - before or after the block it's lying on... That means that either the sand falls down and then completely modifies the map where the sand previously seated, or that everything is OK. So there is a 50% chance that the map will be modified looking at each block! I'd recommend placing gravity-affected blocks lastly. Then there won't be any problems. To mention it, this problem did not exist in the 1.8 version.
Greetings!

**Comment by mepeisen** [comment]
Should be the migration to smart reset.  This feature does not reset all blocks at once. Instead it reset only the blocks  that were changed. Because of java hashmap the blocks are reset in random order.
Ich will change it to sort the blocks by level. So that the lower block (smallest y coordinate) is always resetted first. You can test the fix in about 10 hours as soon as i am home again.

**Comment by mepeisen** [comment]
did the fix solve your problem?
